
# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   socket: /tmp/mysql.sock

# development:
#   <<: *default
#   database: protospace_39258_development


# test:
#   <<: *default
#   database: protospace_39258_test


# production:
#   <<: *default
#   database: protospace_39258_production
#   username: protospace_39258
#   password: <%= ENV['PROTOSPACE_39258_DATABASE_PASSWORD'] %>
#
#
default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: ajax_app_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: ajax_app_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  
